name: Daily Countdown

on:
  schedule:
    - cron: "0 16 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node update.js

      - name: Commit and Push
        run: |
          git config user.name "user"
          git config user.email "mail"

          git add README.md contador.json

          if ! git diff --cached --quiet; then
            git commit -m "daily update"
            git push origin HEAD
          else
            echo "Nenhuma alteração."
          fi
