name: Daily Countdown

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Run script
        run: node update.js

      - name: Commit and push changes
        run: |
          git config user.name "user"
          git config user.email "mail"

          git add README.md contador.json

          if git diff --cached --quiet; then
            echo "Nenhuma alteração."
          else
            git commit -m "daily update"
            git push origin HEAD
          
