name: Daily Countdown

on:
  schedule:
    - cron: "*/5 * * * *"  # roda a cada 5 minutos (evita spam de 1 min)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Run script
        run: node update.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add README.md contador.json

          if git diff --cached --quiet; then
            echo "Nenhuma alteração."
          else
            git commit -m "daily update"
            git push origin HEAD
          fi
